Repository brodia10/US-Missing-Persons-Database, pull requests merged in 2021-02, with the labels that each got.

#4 Import data
  config/settings/base.py
  config/settings/local.py
  us_missing_persons/national_parks/admin.py
  us_missing_persons/national_parks/migrations/0005_auto_20210220_1531.py
  us_missing_persons/national_parks/models.py
Labels: backend

#7 staging and production(#6)
  config/settings/production.py
  config/settings/staging.py
Labels: CI

#8 Fix allowed hosts for Heroku
  config/settings/production.py
  config/settings/staging.py
Labels: CI

#17 Update admin portal copy (#16)
  .gitignore
  config/settings/base.py
Labels: backend

#20 Add geodjango
  .gitignore
  Aptfile
  Aptfile.darwin
  README.md
  config/settings/base.py
  docker-compose.yml
  install_system_deps.sh
  makefile
  requirements.min.txt
  usmp/core/admin.py
  usmp/core/management/commands/load_world_boarders.py
  usmp/core/migrations/0001_initial.py
  usmp/core/models.py
  usmp/core/models/__init__.py
  usmp/core/models/world_boarder.py
Labels: backend

#21 Add geodjango
  requirements.txt
Labels: backend

#22 Add geodjango
  Aptfile
  Aptfile.darwin
  config/settings/base.py
  docker-compose.yml
  install_system_deps.sh
  requirements.min.txt
  requirements.txt
Labels: backend

#25 Add os detection, curl and colored output
  install_system_deps.sh
Labels: enhancement

#26 Run unit tests (#18)
  .github/workflows/pr.yml
  config/settings/base.py
  config/settings/test.py
  install_system_deps.sh
  makefile
  usmp/tests/test_core.py
Labels: backend
